//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/SCRIPTS/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""PlayerMovement"",
            ""id"": ""405cef4d-1ce7-4a78-9d2b-2664dac1e773"",
            ""actions"": [
                {
                    ""name"": ""movement"",
                    ""type"": ""PassThrough"",
                    ""id"": ""0c715332-5e35-45ba-841a-f0f9178b2385"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""2c5bbc7d-9dc9-4612-88ab-460d61ec0793"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""27ce7778-a9ae-4d72-9eb3-f37534f9c827"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""eb2310f8-3983-47e4-9743-e56fcfd28788"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""a311346f-5749-47bc-a638-b22d4f63583a"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""17922bfd-4684-444d-827e-958d33f91294"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""LeftStick"",
                    ""id"": ""335933e1-5af1-4e3c-ae7b-6c043d083e93"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""72a8da9c-8a20-4f0a-b3cf-5ecb4b1bf7b9"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b445a42f-a7f7-4acf-ae2f-2dfdeed43468"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""7f3f862f-6b6f-40b9-89cc-03770f3a6788"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""9073ae2c-79c6-46dd-ab0c-905d01bc13a2"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""CameraControls"",
            ""id"": ""296e2d26-24c9-4f09-8f9d-bc7ef6a1ed37"",
            ""actions"": [
                {
                    ""name"": ""camera"",
                    ""type"": ""PassThrough"",
                    ""id"": ""6e6a3280-67ce-418b-9491-8956717c7730"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""RightStick"",
                    ""id"": ""7be4b4f5-e489-48e3-b644-eb854098604e"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": ""ScaleVector2(x=30,y=30)"",
                    ""groups"": """",
                    ""action"": ""camera"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""b4e82ead-c079-4717-b9aa-ef5ae58a56b8"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""camera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""9a95a3d8-2e72-459f-bc61-4686be538a4f"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""camera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""2f1f40f6-ba69-453f-86f6-667319305b29"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""camera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""36d3f7cd-bac1-4095-90cd-64a318d32eb5"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""camera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""b7dc5db5-9d45-44f9-a94e-9340e299347a"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""camera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PlayerActionButtons"",
            ""id"": ""0b2cb0f6-a746-4307-9c44-27df1663edd4"",
            ""actions"": [
                {
                    ""name"": ""SprintDodge"",
                    ""type"": ""Button"",
                    ""id"": ""d50932e0-ad19-4a5c-a2d1-9853ad20e810"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Keyboard Walk"",
                    ""type"": ""Button"",
                    ""id"": ""9c2d2c1a-ad0b-45fc-aa1d-9c6ba53c94d2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""JumpA/Xbutton"",
                    ""type"": ""Button"",
                    ""id"": ""3a9172d8-b203-41a6-af26-ca8b519d7e1c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack/R1"",
                    ""type"": ""Button"",
                    ""id"": ""aa78327e-a46e-4f1c-b0e8-3901da613cdf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Block/L1"",
                    ""type"": ""Button"",
                    ""id"": ""171df35e-1ad4-4c28-9168-debf5733993b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""48c9ce80-41b2-4a16-aef6-b2d8e236165f"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SprintDodge"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dcd47d8c-bb0b-4501-9ee1-62ae2cf2af1e"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SprintDodge"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d671a2ca-d212-4f1b-b8ed-4a7363c84b59"",
                    ""path"": ""<Keyboard>/leftAlt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Keyboard Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""430a94eb-ba33-4bc9-8313-e3d731036b41"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""JumpA/Xbutton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2d12d676-6caa-4d5c-84e7-c95bcb22082c"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""JumpA/Xbutton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""69da0a9b-6e57-4ae4-82c7-93ae6ddda42c"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack/R1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""11aae490-faa8-4622-ba2d-5e26970f4717"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack/R1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a8bb781f-ad22-4d70-bc4b-ac1902e5b6a2"",
                    ""path"": ""<DualShockGamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack/R1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""36068e3d-9675-4621-a1ca-579dec5a1604"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Block/L1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a2ba5441-02a2-4c16-81b3-fbf96c8dc65c"",
                    ""path"": ""<DualShockGamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Block/L1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9b8bfc70-54f6-47f1-847f-f6e1d4f265d0"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Block/L1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerMovement
        m_PlayerMovement = asset.FindActionMap("PlayerMovement", throwIfNotFound: true);
        m_PlayerMovement_movement = m_PlayerMovement.FindAction("movement", throwIfNotFound: true);
        // CameraControls
        m_CameraControls = asset.FindActionMap("CameraControls", throwIfNotFound: true);
        m_CameraControls_camera = m_CameraControls.FindAction("camera", throwIfNotFound: true);
        // PlayerActionButtons
        m_PlayerActionButtons = asset.FindActionMap("PlayerActionButtons", throwIfNotFound: true);
        m_PlayerActionButtons_SprintDodge = m_PlayerActionButtons.FindAction("SprintDodge", throwIfNotFound: true);
        m_PlayerActionButtons_KeyboardWalk = m_PlayerActionButtons.FindAction("Keyboard Walk", throwIfNotFound: true);
        m_PlayerActionButtons_JumpAXbutton = m_PlayerActionButtons.FindAction("JumpA/Xbutton", throwIfNotFound: true);
        m_PlayerActionButtons_AttackR1 = m_PlayerActionButtons.FindAction("Attack/R1", throwIfNotFound: true);
        m_PlayerActionButtons_BlockL1 = m_PlayerActionButtons.FindAction("Block/L1", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerMovement
    private readonly InputActionMap m_PlayerMovement;
    private List<IPlayerMovementActions> m_PlayerMovementActionsCallbackInterfaces = new List<IPlayerMovementActions>();
    private readonly InputAction m_PlayerMovement_movement;
    public struct PlayerMovementActions
    {
        private @PlayerControls m_Wrapper;
        public PlayerMovementActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @movement => m_Wrapper.m_PlayerMovement_movement;
        public InputActionMap Get() { return m_Wrapper.m_PlayerMovement; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerMovementActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerMovementActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerMovementActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerMovementActionsCallbackInterfaces.Add(instance);
            @movement.started += instance.OnMovement;
            @movement.performed += instance.OnMovement;
            @movement.canceled += instance.OnMovement;
        }

        private void UnregisterCallbacks(IPlayerMovementActions instance)
        {
            @movement.started -= instance.OnMovement;
            @movement.performed -= instance.OnMovement;
            @movement.canceled -= instance.OnMovement;
        }

        public void RemoveCallbacks(IPlayerMovementActions instance)
        {
            if (m_Wrapper.m_PlayerMovementActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerMovementActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerMovementActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerMovementActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerMovementActions @PlayerMovement => new PlayerMovementActions(this);

    // CameraControls
    private readonly InputActionMap m_CameraControls;
    private List<ICameraControlsActions> m_CameraControlsActionsCallbackInterfaces = new List<ICameraControlsActions>();
    private readonly InputAction m_CameraControls_camera;
    public struct CameraControlsActions
    {
        private @PlayerControls m_Wrapper;
        public CameraControlsActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @camera => m_Wrapper.m_CameraControls_camera;
        public InputActionMap Get() { return m_Wrapper.m_CameraControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CameraControlsActions set) { return set.Get(); }
        public void AddCallbacks(ICameraControlsActions instance)
        {
            if (instance == null || m_Wrapper.m_CameraControlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CameraControlsActionsCallbackInterfaces.Add(instance);
            @camera.started += instance.OnCamera;
            @camera.performed += instance.OnCamera;
            @camera.canceled += instance.OnCamera;
        }

        private void UnregisterCallbacks(ICameraControlsActions instance)
        {
            @camera.started -= instance.OnCamera;
            @camera.performed -= instance.OnCamera;
            @camera.canceled -= instance.OnCamera;
        }

        public void RemoveCallbacks(ICameraControlsActions instance)
        {
            if (m_Wrapper.m_CameraControlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICameraControlsActions instance)
        {
            foreach (var item in m_Wrapper.m_CameraControlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CameraControlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CameraControlsActions @CameraControls => new CameraControlsActions(this);

    // PlayerActionButtons
    private readonly InputActionMap m_PlayerActionButtons;
    private List<IPlayerActionButtonsActions> m_PlayerActionButtonsActionsCallbackInterfaces = new List<IPlayerActionButtonsActions>();
    private readonly InputAction m_PlayerActionButtons_SprintDodge;
    private readonly InputAction m_PlayerActionButtons_KeyboardWalk;
    private readonly InputAction m_PlayerActionButtons_JumpAXbutton;
    private readonly InputAction m_PlayerActionButtons_AttackR1;
    private readonly InputAction m_PlayerActionButtons_BlockL1;
    public struct PlayerActionButtonsActions
    {
        private @PlayerControls m_Wrapper;
        public PlayerActionButtonsActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @SprintDodge => m_Wrapper.m_PlayerActionButtons_SprintDodge;
        public InputAction @KeyboardWalk => m_Wrapper.m_PlayerActionButtons_KeyboardWalk;
        public InputAction @JumpAXbutton => m_Wrapper.m_PlayerActionButtons_JumpAXbutton;
        public InputAction @AttackR1 => m_Wrapper.m_PlayerActionButtons_AttackR1;
        public InputAction @BlockL1 => m_Wrapper.m_PlayerActionButtons_BlockL1;
        public InputActionMap Get() { return m_Wrapper.m_PlayerActionButtons; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActionButtonsActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActionButtonsActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionButtonsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionButtonsActionsCallbackInterfaces.Add(instance);
            @SprintDodge.started += instance.OnSprintDodge;
            @SprintDodge.performed += instance.OnSprintDodge;
            @SprintDodge.canceled += instance.OnSprintDodge;
            @KeyboardWalk.started += instance.OnKeyboardWalk;
            @KeyboardWalk.performed += instance.OnKeyboardWalk;
            @KeyboardWalk.canceled += instance.OnKeyboardWalk;
            @JumpAXbutton.started += instance.OnJumpAXbutton;
            @JumpAXbutton.performed += instance.OnJumpAXbutton;
            @JumpAXbutton.canceled += instance.OnJumpAXbutton;
            @AttackR1.started += instance.OnAttackR1;
            @AttackR1.performed += instance.OnAttackR1;
            @AttackR1.canceled += instance.OnAttackR1;
            @BlockL1.started += instance.OnBlockL1;
            @BlockL1.performed += instance.OnBlockL1;
            @BlockL1.canceled += instance.OnBlockL1;
        }

        private void UnregisterCallbacks(IPlayerActionButtonsActions instance)
        {
            @SprintDodge.started -= instance.OnSprintDodge;
            @SprintDodge.performed -= instance.OnSprintDodge;
            @SprintDodge.canceled -= instance.OnSprintDodge;
            @KeyboardWalk.started -= instance.OnKeyboardWalk;
            @KeyboardWalk.performed -= instance.OnKeyboardWalk;
            @KeyboardWalk.canceled -= instance.OnKeyboardWalk;
            @JumpAXbutton.started -= instance.OnJumpAXbutton;
            @JumpAXbutton.performed -= instance.OnJumpAXbutton;
            @JumpAXbutton.canceled -= instance.OnJumpAXbutton;
            @AttackR1.started -= instance.OnAttackR1;
            @AttackR1.performed -= instance.OnAttackR1;
            @AttackR1.canceled -= instance.OnAttackR1;
            @BlockL1.started -= instance.OnBlockL1;
            @BlockL1.performed -= instance.OnBlockL1;
            @BlockL1.canceled -= instance.OnBlockL1;
        }

        public void RemoveCallbacks(IPlayerActionButtonsActions instance)
        {
            if (m_Wrapper.m_PlayerActionButtonsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActionButtonsActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionButtonsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionButtonsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActionButtonsActions @PlayerActionButtons => new PlayerActionButtonsActions(this);
    public interface IPlayerMovementActions
    {
        void OnMovement(InputAction.CallbackContext context);
    }
    public interface ICameraControlsActions
    {
        void OnCamera(InputAction.CallbackContext context);
    }
    public interface IPlayerActionButtonsActions
    {
        void OnSprintDodge(InputAction.CallbackContext context);
        void OnKeyboardWalk(InputAction.CallbackContext context);
        void OnJumpAXbutton(InputAction.CallbackContext context);
        void OnAttackR1(InputAction.CallbackContext context);
        void OnBlockL1(InputAction.CallbackContext context);
    }
}
